### ISSUE TITLE
Flamegraph does not match table data and callgraph

### ISSUE THREAD

**Issue by josdagaro** [perftools/xhgui#212] opened 2017-10-19 19:56 UTC
The function main inclusive wall time value is the sum of the time invested in itself in addition to its children, this value is correct in the flamegraph, but in the callgraph and table data the values aren't the same.

![3](https://user-images.githubusercontent.com/17706518/31791287-b71233d2-b4dd-11e7-9d69-be50d1f9c944.png)
________________________________________________________________________________________________________
![1](https://user-images.githubusercontent.com/17706518/31791288-b72a60e2-b4dd-11e7-9032-eff741528df6.png)
________________________________________________________________________________________________________
![2](https://user-images.githubusercontent.com/17706518/31791289-b73c95d2-b4dd-11e7-8015-6a09fc08520e.png)

**Comment by josdagaro** [comment] 2017-10-19 19:57
I need help understanding this.

**Comment by michaelbutler** [comment] 2017-10-19 20:04
I think there is a bug in the flamegraph. Notice how on the main `Recent runs` page it says 150ms wall time, that's the overall time it took for the whole request. You can confirm using chrome network inspector. The callgraph also shows `main()` taking 150ms wall time, also correct. The flamegraph says 454ms, that is not correct.  The reason for this is that it adds the total time (150ms) plus the total time of all children, greatly inflating the value. 

Bug ticket opened here https://github.com/perftools/xhgui/issues/207 though I have not had a chance to fix it.

**Comment by michaelbutler** [comment] 2017-10-19 20:05
sidenote: check your server charset settings, looks like you are possibly serving up ISO-8859-1 encoding instead of UTF-8.

**Comment by josdagaro** [comment] 2017-10-19 21:18
I'm confused, if the flamegraph is incorrect, ¿how is the total wall time calculated?

**Comment by josdagaro** [comment] 2017-10-19 21:39
The inclusive wall time of main function is the sum of all its secondary functions, ¿right? So, ¿why is the sum of the self wall times of their children not equivalent to the inclusive wall time of the main function?

**Comment by markstory** [comment] 2017-10-20 00:52
> So, ¿why is the sum of the self wall times of their children not equivalent to the inclusive wall time of the main function?

It should be close, but it won't be exact as xhprof is not able to capture 100% of every operation, there is always a bit of slippage/loss.

**Comment by josdagaro** [comment] 2017-10-20 14:05
Check this:
![1](https://user-images.githubusercontent.com/17706518/31824527-e7dd0a40-b574-11e7-813b-b23080fcc0e9.png)
![2](https://user-images.githubusercontent.com/17706518/31824528-e806ca24-b574-11e7-9762-f5c97b92123f.png)
![3](https://user-images.githubusercontent.com/17706518/31824529-e81fd42e-b574-11e7-9ecd-fc3e9dcc3af9.png)
![4](https://user-images.githubusercontent.com/17706518/31824531-e839aa5c-b574-11e7-97bd-7bd9607f8269.png)
![5](https://user-images.githubusercontent.com/17706518/31824532-e87c0b0e-b574-11e7-94a5-11d8b5e5b993.png)
![6](https://user-images.githubusercontent.com/17706518/31824533-e8af7476-b574-11e7-9dd3-877e44937033.png)

¿Can you see that for me the most logical graph is flamegraph? The sum seems correct, but in the callgraph I do not understand why the time is different:

`
Flamegraph: CI_DB_driver::simple_query (44,176 ms) + pg_connect (20,067 ms) = CI_DB_postgre_driver::db_connect (62,0243)

Callgraph: CI_DB_driver::simple_query (44,176 ms) + pg_connect (20,067 ms) = CI_DB_postgre_driver::db_connect (32,229)
`

More information:

![7](https://user-images.githubusercontent.com/17706518/31824804-c758247a-b575-11e7-844e-5c787124fcf2.png)

Please, help me to understand it.

**Comment by michaelbutler** [comment] 2017-10-20 14:30
First you need to find out what is really the true correct inclusive wall time values.

Your data (the index table, which should be the correct thing) is reporting that db_connect took 32ms inclusive wall time... that means it took 32ms if you did something like this:

```php
$t = microtime(true);
whatever->db_connect()
error_log(microtime(true) - $t);
```

Most surely that is correct, but please confirm by actually using that snippet above and writing the value with `error_log`. Next, use the same snippet to get the overall time of your request:

```php
$t = microtime(true);
MyApplication::run(); // whatever the main entry point to your app that does everything.
error_log(microtime(true) - $t);
```

**Comment by markstory** [comment] 2017-10-20 20:57
You could also look at the data in mongodb. If xhprof has recorded the data 'wrong' we can never make the page look right.

**Comment by josdagaro** [comment] 2017-10-23 15:15
I'm very confused, ¿is it possible that "self wall time" is greater than "inclusive wall time"?

**Comment by michaelbutler** [comment] 2017-10-23 19:37
Inclusive Wall Time will always be greater than Self Wall Time.

**Comment by josdagaro** [comment] 2017-10-23 19:55
Oh, right, I saw wrong..., I thought time was 468,000 but is just 468; my error.
Ok, I saw this page from a third party: [xhprof](http://xhprof.tk) and the results are the same.

**Comment by josdagaro** [comment] 2017-10-23 19:57
¿Is the wall time sum in the flamegraph the same of callgraph?

**Comment by markstory** [comment] 2017-10-24 01:04
> Is the wall time sum in the flamegraph the same of callgraph?

It should be. The callgraph and flamegraph use the same data under the hood.

**Comment by Krinkle** [comment] 2017-11-14 06:51
This is a duplicate of https://github.com/perftools/xhgui/issues/207.

**Comment by Krinkle** [comment] 2018-09-16 17:47
>> markstory  wrote at https://github.com/perftools/xhgui/pull/216#issuecomment-399806458:
>  Last I remember there were different display issues with these changes. I haven't had much time to dedicate to this project as of late though.

@markstory Yes, the display issues that are made apparent by https://github.com/perftools/xhgui/pull/216, however, the issue is pre-existent.

In my opinion, the current flame graph implementation is almost useless, and highly deceptive. The only reason it doesn't look broken is due to various bugs cancelling each other out. But a close look at any part of the stack, exposes its information to be non-sensical.

I looked at this earlier when we talked at https://github.com/perftools/xhgui/pull/216, but after another very confusing debug round today, I realised the problem is much bigger than I thought. Below is an example:

### Actual call tree
(Unbeknownst to xhprof)

* main() - [wt: 1000ms]
  * 1x smallStuff() [wt: 100ms]
    * 1x process('small') [wt: 100ms]
      * 10x processOne() [wt: 100ms, 10ms each]
  * 1x bigStuff() [wt: 900ms]
    * 1x process('big') [wt: 900ms]
      * 90x processOne() [wt: 900ms, 10ms each]

### stacks
From xhprof (unsampled)

```
main() => smallStuff()    [ c: 1, wt: 100ms ]
main() => bigStuff()      [ c: 1, wt: 900ms ]
smallStuff() => process() [ c: 1, wt: 100ms ]
bigStuff() => process()   [ c: 1, wt: 900ms ]
process() => processOne() [ c: 100, wt: 1000ms ]
```

### flamegraph-data

XHGui currently converts the above as follows:

```php
            'data' => array(
                'name' => 'main()',
                'value' => 1000,
                'children' => array(
                    array(
                        'name' => 'smallStuff()',
                        'value' => 100,
                        'children' => array(
                            array(
                                'name' => 'process()',
                                'value' => 1000, # bigger than parent
                                'children' => array(
                                    array(
                                        'name' => 'processOne()',
                                        'value' => 1000,
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array(
                        'name' => 'bigStuff()',
                        'value' => 900,
                        'children' => array(
                            array(
                                'name' => 'process()',
                                'value' => 1000 # bigger than parent
                            ),
                        ),
                    ),
                ),
            ),
            'sort' => array(
                'main()' => 0,
                'smallStuff()' => 1,
                'bigStuff()' => 4,
                'process()' => 2,
                'processOne()' => 3,
            )
```

### flamegraph-visual

* main() – 2000ms
  * smallStuff() – 1000ms
    * process() – 1000ms
      * processOne() – 1000ms
   * bigStuff() – 100ms
    * process() – 1000ms

<img width="1409" alt="screen shot 2018-09-16 at 18 25 38" src="https://user-images.githubusercontent.com/156867/45599116-00acc100-b9de-11e8-81a8-e8a1f2fb3b36.png">

I originally thought that the only problem was that D3-flamegraph sees each node as self-time (instead of inclusive time, per https://github.com/perftools/xhgui/issues/207). But that is not exactly the case.

If D3-flamegraph was seeing each node reporting self-time then smallStuff/process would be computed as 2000ms (1000 self, 1000 of its children), and smallStuff as 3000ms, etc..

In actuality, D3-flamegraph is throwing away 90% of all timing data, in favour of only summing the leaf nodes. This means any time spent in any method anywhere in the system, unless it is a leaf node, it is not represented in the graph.

Of course, the problem is not that D3-flamegraph is using a wrong formula for aggregating self-time.  The problem is that it tries to aggregate at all, because the XHProf data is not self-time, it is already aggregated.

Problems with old D3-flamegraph:
* It discards all time spent in any method, except for leaf nodes.
* It replaces the time for each method with the sum of the descendant leaf nodes.
* The time spent in `main()` is often 10x or 1000x larger than it should be.
* The overall proportions are incorrect. Slow code can appear fast, fast code can appear slow. If the problem was that it was doing self-time aggregation only (and doing it correctly), it would at least have correct overall proportions (although it would be exaggerated in that case).

Problems with flamegraph-data export:
* Whenever a duplicate pair of parent>child is seen, only the first encounter (seemingly random) gets a child stack. The rest will have no children.

**Comment by markstory** [comment] 2018-09-17 20:49
I'm ok with removing the flamegraph output entirely. If its not helpful and can't be made helpful there is no point in keeping int.

**Comment by Krinkle** [comment] 2018-09-17 21:52
@markstory Yeah, I'm sad to see it go, but in the short-medium term we should probably look into the Callgraph visualisation instead.

Callgraph is a bit harder to navigate, but is true to the data and super accurate. In it also useful in ways that Flamegraphs can't be, such as visually emphasising methods that are called a lot and take much time, but are called from different sub-trees. The Callgraph shows that time combined really well.

Would you accept a PR that removes the component?

**Comment by markstory** [comment] 2018-09-19 03:53
> Would you accept a PR that removes the component?

Yes :+1:

**Closed** 2018-09-24 00:51 UTC
